insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Grand Carsavan', 1996, 'O73-18');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Stratus', 1997, 'V91-43');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lincoln', 'Navigator', 2009, 'K72-74');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', '5000CS', 1988, 'V57-21');
insert into Cars (Brand, Model, Year, Regnumber) values ('Honda', 'CR-V', 1999, 'A82-39');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Ram Wagon B350', 1992, 'R18-23');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'Eos', 2008, 'W32-67');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', 'SL-Class', 1997, 'R25-41');
insert into Cars (Brand, Model, Year, Regnumber) values ('Porsche', '928', 1990, 'O73-18');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'HHR', 2011, 'P57-61');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lamborghini', 'Murciélago', 2004, 'C34-11');
insert into Cars (Brand, Model, Year, Regnumber) values ('Kia', 'Sedona', 2010, 'I68-81');
insert into Cars (Brand, Model, Year, Regnumber) values ('Isuzu', 'i-370', 2007, 'K41-24');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', 'CL-Class', 2010, 'N11-92');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Corsica', 1994, 'Q59-63');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', '1000', 1985, 'H81-49');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Outlander', 2005, 'N22-93');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', 'Quattro', 1985, 'B88-81');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lincoln', 'Blackwood', 2003, 'G79-64');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Colorado', 2009, 'C28-47');
insert into Cars (Brand, Model, Year, Regnumber) values ('Rolls-Royce', 'Phantom', 2005, 'W19-28');
insert into Cars (Brand, Model, Year, Regnumber) values ('Hummer', 'H1', 1993, 'G91-75');
insert into Cars (Brand, Model, Year, Regnumber) values ('Infiniti', 'FX', 2010, 'K91-57');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'G-Series G10', 1993, 'Y45-59');
insert into Cars (Brand, Model, Year, Regnumber) values ('BMW', 'M3', 2004, 'E14-71');
insert into Cars (Brand, Model, Year, Regnumber) values ('Honda', 'S2000', 2001, 'Y34-86');
insert into Cars (Brand, Model, Year, Regnumber) values ('Honda', 'Prelude', 1986, 'B49-13');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Ram 3500 Club', 1997, 'O25-76');
insert into Cars (Brand, Model, Year, Regnumber) values ('Isuzu', 'Ascender', 2008, 'P52-55');
insert into Cars (Brand, Model, Year, Regnumber) values ('Jeep', 'Commander', 2010, 'A44-85');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Camry', 2004, 'D65-52');
insert into Cars (Brand, Model, Year, Regnumber) values ('Nissan', 'Frontier', 2008, 'I69-27');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', 'Sprinter 3500', 2011, 'K77-64');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Ram 3500', 1994, 'X15-83');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volvo', 'V90', 1998, 'D12-27');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', '1500 Club Coupe', 1998, 'X23-35');
insert into Cars (Brand, Model, Year, Regnumber) values ('BMW', '3 Series', 2006, 'E45-78');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volvo', 'C70', 2000, 'O55-28');
insert into Cars (Brand, Model, Year, Regnumber) values ('Nissan', 'Titan', 2005, 'W65-26');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Sienna', 2003, 'F61-18');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', 'Bonneville', 1998, 'Z96-56');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Econoline E350', 1992, 'O76-21');
insert into Cars (Brand, Model, Year, Regnumber) values ('Acura', 'NSX', 1994, 'Y16-34');
insert into Cars (Brand, Model, Year, Regnumber) values ('Oldsmobile', 'LSS', 1997, 'W75-21');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', 'Q5', 2009, 'F92-24');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', 'Mazda5', 2012, 'F18-46');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Mustang', 1996, 'G72-88');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'MR2', 2000, 'F93-61');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', '100', 1992, 'D47-55');
insert into Cars (Brand, Model, Year, Regnumber) values ('Plymouth', 'Roadrunner', 1969, 'C28-39');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'F250', 1997, 'Q11-51');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', 'A7', 2012, 'R18-23');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Cavalier', 2005, 'Q39-85');
insert into Cars (Brand, Model, Year, Regnumber) values ('Buick', 'LaCrosse', 2005, 'I77-37');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', 'Cabriolet', 1998, 'H81-49');
insert into Cars (Brand, Model, Year, Regnumber) values ('Porsche', 'Cayenne', 2004, 'Z12-93');
insert into Cars (Brand, Model, Year, Regnumber) values ('Cadillac', 'Eldorado', 1997, 'L81-56');
insert into Cars (Brand, Model, Year, Regnumber) values ('Kia', 'Soul', 2012, 'N26-12');
insert into Cars (Brand, Model, Year, Regnumber) values ('Nissan', 'Altima', 2013, 'H15-95');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'Scirocco', 1984, 'M44-84');
insert into Cars (Brand, Model, Year, Regnumber) values ('Acura', 'CL', 2001, 'H98-99');
insert into Cars (Brand, Model, Year, Regnumber) values ('Jaguar', 'XK Series', 2013, 'Z65-33');
insert into Cars (Brand, Model, Year, Regnumber) values ('BMW', 'Z8', 2002, 'V13-85');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Focus ST', 2013, 'S53-62');
insert into Cars (Brand, Model, Year, Regnumber) values ('Nissan', 'Altima', 1994, 'W89-64');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercury', 'Grand Marquis', 1990, 'S31-35');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Festiva', 1989, 'F73-34');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Jimmy', 2001, 'Z82-98');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lincoln', 'MKZ', 2008, 'I76-11');
insert into Cars (Brand, Model, Year, Regnumber) values ('Scion', 'xB', 2012, 'W19-24');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volvo', 'V70', 2008, 'D36-88');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Durango', 2003, 'X76-68');
insert into Cars (Brand, Model, Year, Regnumber) values ('Jaguar', 'XJ', 2008, 'V69-93');
insert into Cars (Brand, Model, Year, Regnumber) values ('Honda', 'Fit', 2010, 'A57-86');
insert into Cars (Brand, Model, Year, Regnumber) values ('Suzuki', 'Swift', 1992, 'N66-75');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Solara', 2007, 'Y51-16');
insert into Cars (Brand, Model, Year, Regnumber) values ('BMW', 'X5', 2008, 'N94-92');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Neon', 1996, 'D91-29');
insert into Cars (Brand, Model, Year, Regnumber) values ('Infiniti', 'QX', 1997, 'J88-89');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', 'Miata MX-5', 2012, 'E45-78');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Rally Wagon 2500', 1994, 'L56-21');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Express 3500', 2000, 'M24-75');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', 'SL-Class', 2004, 'V68-36');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Durango', 2003, 'G72-88');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Carsavan', 2012, 'L33-37');
insert into Cars (Brand, Model, Year, Regnumber) values ('Subaru', 'Legacy', 2002, 'H67-87');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', '2500', 1993, 'I78-76');
insert into Cars (Brand, Model, Year, Regnumber) values ('Suzuki', 'Vitara', 2001, 'G89-25');
insert into Cars (Brand, Model, Year, Regnumber) values ('Suzuki', 'Sidekick', 1998, 'Z36-76');
insert into Cars (Brand, Model, Year, Regnumber) values ('Cadillac', 'Seville', 1995, 'M63-15');
insert into Cars (Brand, Model, Year, Regnumber) values ('Acura', 'TSX', 2004, 'Q17-16');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Intrepid', 1996, 'T17-45');
insert into Cars (Brand, Model, Year, Regnumber) values ('Jaguar', 'XK', 2012, 'F81-96');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', 'CLS-Class', 2006, 'S53-62');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lincoln', 'Continental', 2002, 'C15-72');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', '1500 Club Coupe', 1999, 'J27-56');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lexus', 'GS', 1993, 'H67-87');
insert into Cars (Brand, Model, Year, Regnumber) values ('Oldsmobile', 'Silhouette', 1996, 'G78-44');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', 'Protege', 2000, 'D34-47');
insert into Cars (Brand, Model, Year, Regnumber) values ('Isuzu', 'Trooper', 1999, 'H43-59');
insert into Cars (Brand, Model, Year, Regnumber) values ('Hyundai', 'Elantra', 2013, 'C53-29');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Thunderbird', 1986, 'C25-81');
insert into Cars (Brand, Model, Year, Regnumber) values ('Acura', 'TL', 2005, 'C35-66');
insert into Cars (Brand, Model, Year, Regnumber) values ('BMW', '3 Series', 2004, 'B27-42');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', 'MX-6', 1991, 'O16-74');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Ram 3500', 2009, 'M23-12');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', 'A5', 2012, 'L21-53');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercury', 'Sable', 1987, 'M48-57');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volvo', '960', 1992, 'A81-16');
insert into Cars (Brand, Model, Year, Regnumber) values ('Isuzu', 'Hombre Space', 1998, 'X59-93');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Windstar', 2000, 'Z11-89');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Vandura G3500', 1996, 'C86-35');
insert into Cars (Brand, Model, Year, Regnumber) values ('Hyundai', 'Santa Fe', 2005, 'L58-87');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'Touareg', 2007, 'G14-13');
insert into Cars (Brand, Model, Year, Regnumber) values ('Acura', 'RL', 2006, 'B85-59');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', 'Bonneville', 1967, 'W52-15');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Thunderbird', 1983, 'C15-72');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', 'S6', 2002, 'H93-96');
insert into Cars (Brand, Model, Year, Regnumber) values ('Acura', 'Integra', 1999, 'A57-86');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', '1500', 1993, 'K91-57');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', 'G6', 2005, 'L81-56');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Ram 1500', 2009, 'S34-27');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'E-Series', 1963, 'J27-56');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Suburban 1500', 2000, 'L21-53');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Montero', 1993, 'H72-43');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Canyon', 2009, 'F81-98');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Mustang', 2002, 'X66-97');
insert into Cars (Brand, Model, Year, Regnumber) values ('Nissan', 'Altima', 2000, 'D12-27');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Venture', 2000, 'G72-88');
insert into Cars (Brand, Model, Year, Regnumber) values ('Hyundai', 'Accent', 2010, 'V87-88');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'F-Series', 1985, 'C15-32');
insert into Cars (Brand, Model, Year, Regnumber) values ('Isuzu', 'VehiCROSS', 2001, 'Q51-78');
insert into Cars (Brand, Model, Year, Regnumber) values ('Oldsmobile', 'Silhouette', 1994, 'J27-15');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'D150', 1993, 'I27-59');
insert into Cars (Brand, Model, Year, Regnumber) values ('Honda', 'Prelude', 1993, 'Q86-69');
insert into Cars (Brand, Model, Year, Regnumber) values ('Honda', 'CR-V', 2003, 'F85-18');
insert into Cars (Brand, Model, Year, Regnumber) values ('MG', 'MGB', 1977, 'S34-27');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'GT500', 2008, 'Y63-62');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Ram 1500', 1997, 'T95-99');
insert into Cars (Brand, Model, Year, Regnumber) values ('Rolls-Royce', 'Phantom', 2011, 'Q75-24');
insert into Cars (Brand, Model, Year, Regnumber) values ('MINI', 'Clubman', 2008, 'I22-96');
insert into Cars (Brand, Model, Year, Regnumber) values ('Buick', 'Regal', 1996, 'H67-87');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volvo', 'XC90', 2005, 'B99-92');
insert into Cars (Brand, Model, Year, Regnumber) values ('Jeep', 'Grand Cherokee', 2006, 'C28-47');
insert into Cars (Brand, Model, Year, Regnumber) values ('Suzuki', 'XL7', 2007, 'Q75-13');
insert into Cars (Brand, Model, Year, Regnumber) values ('Kia', 'Soul', 2010, 'K49-35');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Venza', 2011, 'T16-98');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Explorer', 2004, 'D63-34');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Yaris', 2006, 'O37-23');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Camry', 2000, 'B98-46');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chrysler', 'Sebring', 2008, 'N47-98');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Paseo', 1996, 'V34-35');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Yukon XL 2500', 2004, 'B54-87');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'F250', 2006, 'H43-59');
insert into Cars (Brand, Model, Year, Regnumber) values ('Daihatsu', 'Rocky', 1992, 'W13-13');
insert into Cars (Brand, Model, Year, Regnumber) values ('Cadillac', 'Escalade ESV', 2004, 'L63-92');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Solara', 2005, 'O37-23');
insert into Cars (Brand, Model, Year, Regnumber) values ('Plymouth', 'Roadrunner', 1969, 'K66-42');
insert into Cars (Brand, Model, Year, Regnumber) values ('Acura', 'SLX', 1996, 'K14-51');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Ram Van B250', 1992, 'A57-86');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'F-Series', 2009, 'G79-64');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', 'A8', 2006, 'L54-81');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Mirage', 1993, 'U95-67');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', 'A3', 2011, 'N57-11');
insert into Cars (Brand, Model, Year, Regnumber) values ('Honda', 'Civic', 1991, 'T46-28');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercury', 'Mountaineer', 2003, 'C53-29');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', 'A8', 2009, 'W75-19');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', 'B-Series', 2003, 'K64-13');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Yukon', 2012, 'J58-65');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', 'Firebird', 2000, 'K76-26');
insert into Cars (Brand, Model, Year, Regnumber) values ('Nissan', 'Rogue', 2008, 'M54-68');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', 'MPV', 2003, 'G34-54');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Grand Carsavan', 2007, 'Y54-69');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'E-Series', 1987, 'B55-18');
insert into Cars (Brand, Model, Year, Regnumber) values ('Oldsmobile', 'Ciera', 1994, 'G75-71');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', 'S4', 1994, 'R94-69');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', 'S4', 1993, 'B31-38');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Astro', 2005, 'S46-36');
insert into Cars (Brand, Model, Year, Regnumber) values ('Jeep', 'Grand Cherokee', 2007, 'Z75-25');
insert into Cars (Brand, Model, Year, Regnumber) values ('BMW', 'Z4 M', 2006, 'M79-67');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'TundraMax', 2008, 'A83-33');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Mustang', 2011, 'K91-57');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lexus', 'RX', 2013, 'X72-31');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Mirage', 1986, 'F94-55');
insert into Cars (Brand, Model, Year, Regnumber) values ('Plymouth', 'Neon', 2001, 'U68-87');
insert into Cars (Brand, Model, Year, Regnumber) values ('Honda', 'S2000', 2004, 'M86-22');
insert into Cars (Brand, Model, Year, Regnumber) values ('Land Rover', 'Range Rover', 1994, 'C73-52');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Montero', 2004, 'J22-32');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lotus', 'Elan', 1994, 'J24-95');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Celica', 1992, 'K14-23');
insert into Cars (Brand, Model, Year, Regnumber) values ('Hyundai', 'Sonata', 2006, 'T32-67');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Sequoia', 2007, 'B85-59');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', '626', 1984, 'M21-17');
insert into Cars (Brand, Model, Year, Regnumber) values ('Cadillac', 'Escalade ESV', 2005, 'U34-53');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', 'SL-Class', 1985, 'Q14-33');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volvo', 'S80', 2006, 'Z89-73');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Camaro', 2000, 'W58-95');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Silverado 3500', 2011, 'B14-53');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Highlander', 2002, 'I35-72');
insert into Cars (Brand, Model, Year, Regnumber) values ('Geo', 'Prizm', 1993, 'U36-34');
insert into Cars (Brand, Model, Year, Regnumber) values ('Oldsmobile', 'LSS', 1998, 'V87-88');
insert into Cars (Brand, Model, Year, Regnumber) values ('Morgan', 'Aero 8', 2009, 'V21-96');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Ranger', 1993, 'D67-98');
insert into Cars (Brand, Model, Year, Regnumber) values ('Honda', 'Civic', 2002, 'L38-23');
insert into Cars (Brand, Model, Year, Regnumber) values ('Jaguar', 'X-Type', 2008, 'W61-34');
insert into Cars (Brand, Model, Year, Regnumber) values ('Infiniti', 'QX56', 2007, 'W54-72');
insert into Cars (Brand, Model, Year, Regnumber) values ('Saab', '9-4X', 2011, 'Q51-78');
insert into Cars (Brand, Model, Year, Regnumber) values ('BMW', '6 Series', 2009, 'E75-46');
insert into Cars (Brand, Model, Year, Regnumber) values ('Honda', 'Odyssey', 1999, 'U81-82');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'New Beetle', 2010, 'S53-96');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volvo', 'XC70', 2011, 'Q93-67');
insert into Cars (Brand, Model, Year, Regnumber) values ('Suzuki', 'SJ', 1991, 'Q88-47');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lincoln', 'Continental', 1994, 'C83-35');
insert into Cars (Brand, Model, Year, Regnumber) values ('Jeep', 'Wrangler', 2003, 'H85-12');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Silverado 3500', 2003, 'U36-34');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', 'SLK-Class', 2011, 'S29-64');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', 'S6', 2002, 'W25-11');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Eclipse', 1990, 'F41-56');
insert into Cars (Brand, Model, Year, Regnumber) values ('MINI', 'Countryman', 2011, 'P43-36');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Cruze', 2011, 'D37-22');
insert into Cars (Brand, Model, Year, Regnumber) values ('Infiniti', 'G', 1992, 'G44-92');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Tempo', 1992, 'U68-57');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Expedition', 2006, 'E28-76');
insert into Cars (Brand, Model, Year, Regnumber) values ('Kia', 'Carsens', 2007, 'B43-33');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lexus', 'LS', 1989, 'K25-68');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lincoln', 'Continental', 1996, 'G99-18');
insert into Cars (Brand, Model, Year, Regnumber) values ('Suzuki', 'SX4', 2012, 'F56-84');
insert into Cars (Brand, Model, Year, Regnumber) values ('Hummer', 'H2', 2009, 'X36-25');
insert into Cars (Brand, Model, Year, Regnumber) values ('Suzuki', 'Esteem', 1996, 'T84-94');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Yukon XL 1500', 2004, 'F54-26');
insert into Cars (Brand, Model, Year, Regnumber) values ('Hummer', 'H1', 1998, 'Q38-99');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', 'SL-Class', 2006, 'B27-42');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercury', 'Grand Marquis', 1998, 'C86-35');
insert into Cars (Brand, Model, Year, Regnumber) values ('Scion', 'tC', 2010, 'E94-93');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Corvette', 2003, 'O19-43');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lexus', 'RX Hybrid', 2007, 'Y68-71');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Mustang', 2013, 'W32-67');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Durango', 1999, 'T34-38');
insert into Cars (Brand, Model, Year, Regnumber) values ('Land Rover', 'Range Rover', 2006, 'H63-22');
insert into Cars (Brand, Model, Year, Regnumber) values ('Cadillac', 'Escalade EXT', 2012, 'F81-96');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'E250', 2008, 'J88-89');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', 'MX-5', 2003, 'T84-94');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', 'Mazdaspeed 3', 2012, 'H15-95');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', 'Grand Am', 1988, 'I68-81');
insert into Cars (Brand, Model, Year, Regnumber) values ('Jeep', 'Grand Cherokee', 2009, 'D16-89');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Flex', 2012, 'Q11-51');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chrysler', 'Cirrus', 2000, 'O65-36');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercury', 'Marquis', 1984, 'K54-68');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', 'Firefly', 1994, 'S53-96');
insert into Cars (Brand, Model, Year, Regnumber) values ('Suzuki', 'Daewoo Lacetti', 2006, 'B88-81');
insert into Cars (Brand, Model, Year, Regnumber) values ('Hyundai', 'Tiburon', 2005, 'M49-67');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Suburban', 2009, 'V22-57');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', '6000', 1988, 'B47-93');
insert into Cars (Brand, Model, Year, Regnumber) values ('Buick', 'Century', 1990, 'F22-79');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lamborghini', 'Aventador', 2012, 'G99-92');
insert into Cars (Brand, Model, Year, Regnumber) values ('Acura', 'RDX', 2009, 'E68-44');
insert into Cars (Brand, Model, Year, Regnumber) values ('Hummer', 'H2', 2006, 'Y31-27');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Ram Van 3500', 1995, 'L76-62');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Club Wagon', 1996, 'E51-93');
insert into Cars (Brand, Model, Year, Regnumber) values ('Buick', 'Estate', 1989, 'M81-56');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lincoln', 'Town Cars', 1998, 'K49-29');
insert into Cars (Brand, Model, Year, Regnumber) values ('BMW', 'Z4 M', 2007, 'Q12-37');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercury', 'Grand Marquis', 1990, 'C86-35');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', '500E', 1993, 'S53-62');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Suburban 1500', 1996, 'M93-38');
insert into Cars (Brand, Model, Year, Regnumber) values ('Acura', 'TSX', 2009, 'H59-52');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Grand Carsavan', 1992, 'X82-46');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Tacoma', 2012, 'Z62-19');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercury', 'Cougar', 2002, 'Q51-78');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'GT', 2005, 'M86-33');
insert into Cars (Brand, Model, Year, Regnumber) values ('Rolls-Royce', 'Phantom', 2006, 'G52-25');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Lumina', 1999, 'Z75-28');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'Jetta', 2011, 'G91-75');
insert into Cars (Brand, Model, Year, Regnumber) values ('Nissan', '350Z', 2006, 'R15-91');
insert into Cars (Brand, Model, Year, Regnumber) values ('Saturn', 'Astra', 2008, 'T89-59');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', 'G-Class', 2007, 'N47-98');
insert into Cars (Brand, Model, Year, Regnumber) values ('BMW', '8 Series', 1996, 'C27-65');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lexus', 'SC', 1993, 'Z89-73');
insert into Cars (Brand, Model, Year, Regnumber) values ('MINI', 'Cooper', 2012, 'J98-97');
insert into Cars (Brand, Model, Year, Regnumber) values ('Saab', '9000', 1993, 'W18-46');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Previa', 1997, 'V31-14');
insert into Cars (Brand, Model, Year, Regnumber) values ('Cadillac', 'CTS', 2004, 'Q57-43');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', 'B-Series Plus', 1998, 'S46-36');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Viper', 1999, 'Y62-52');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Focus', 2006, 'E53-91');
insert into Cars (Brand, Model, Year, Regnumber) values ('Nissan', 'Versa', 2012, 'F88-86');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Cobalt', 2007, 'V72-28');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'Golf', 1984, 'P43-36');
insert into Cars (Brand, Model, Year, Regnumber) values ('Isuzu', 'Trooper', 2002, 'N87-46');
insert into Cars (Brand, Model, Year, Regnumber) values ('Cadillac', 'Seville', 2004, 'U34-53');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'Cabriolet', 1987, 'X86-58');
insert into Cars (Brand, Model, Year, Regnumber) values ('Infiniti', 'G35', 2006, 'H36-62');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lotus', 'Elan', 1990, 'Z94-68');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'Golf', 2005, 'H44-29');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ram', '1500', 2011, 'O65-36');
insert into Cars (Brand, Model, Year, Regnumber) values ('Nissan', 'GT-R', 2012, 'A86-61');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Blazer', 2003, 'P29-43');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Camry', 1996, 'C59-75');
insert into Cars (Brand, Model, Year, Regnumber) values ('Isuzu', 'Oasis', 1997, 'O51-39');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lamborghini', 'Diablo', 1996, 'C35-66');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', 'Q5', 2012, 'M44-84');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', '400E', 1992, 'S88-65');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', 'A6', 2006, 'A15-85');
insert into Cars (Brand, Model, Year, Regnumber) values ('Eagle', 'Talon', 1992, 'A86-61');
insert into Cars (Brand, Model, Year, Regnumber) values ('Jaguar', 'X-Type', 2005, 'W89-64');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', '929', 1989, 'T82-68');
insert into Cars (Brand, Model, Year, Regnumber) values ('Nissan', 'Sentra', 1999, 'A56-41');
insert into Cars (Brand, Model, Year, Regnumber) values ('Subaru', 'Tribeca', 2010, 'J98-97');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Tundra', 2010, 'M48-57');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Dynasty', 1992, 'L77-84');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', 'SL-Class', 1989, 'K77-18');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Montero', 1996, 'Z18-97');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', 'M-Class', 2008, 'G44-92');
insert into Cars (Brand, Model, Year, Regnumber) values ('Citroën', 'CX', 1974, 'G19-86');
insert into Cars (Brand, Model, Year, Regnumber) values ('Kia', 'Carsens', 2007, 'L26-94');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Eclipse', 1991, 'E46-54');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Colt', 1992, 'N92-48');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Escape', 2009, 'B72-27');
insert into Cars (Brand, Model, Year, Regnumber) values ('MINI', 'Clubman', 2011, 'S17-77');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lincoln', 'Aviator', 2005, 'U36-34');
insert into Cars (Brand, Model, Year, Regnumber) values ('Nissan', 'Armada', 2005, 'G91-75');
insert into Cars (Brand, Model, Year, Regnumber) values ('BMW', '5 Series', 2002, 'H43-59');
insert into Cars (Brand, Model, Year, Regnumber) values ('Jaguar', 'X-Type', 2008, 'G56-43');
insert into Cars (Brand, Model, Year, Regnumber) values ('Suzuki', 'Forenza', 2005, 'E46-54');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', 'M-Class', 2003, 'Y51-16');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'Touareg 2', 2008, 'Q93-66');
insert into Cars (Brand, Model, Year, Regnumber) values ('Hummer', 'H1', 1994, 'E74-34');
insert into Cars (Brand, Model, Year, Regnumber) values ('Honda', 'Ridgeline', 2008, 'W58-95');
insert into Cars (Brand, Model, Year, Regnumber) values ('Buick', 'Reatta', 1990, 'J49-23');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', 'B-Series Plus', 2001, 'A14-35');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Galant', 1997, 'P33-21');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Sierra 1500', 2012, 'E51-93');
insert into Cars (Brand, Model, Year, Regnumber) values ('MINI', 'MINI', 2002, 'U17-79');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Dakota Club', 2007, 'C92-49');
insert into Cars (Brand, Model, Year, Regnumber) values ('Scion', 'iQ', 2012, 'R12-35');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Silverado 1500', 2010, 'C92-77');
insert into Cars (Brand, Model, Year, Regnumber) values ('Infiniti', 'QX', 2012, 'C15-32');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Blazer', 1993, 'I24-48');
insert into Cars (Brand, Model, Year, Regnumber) values ('Porsche', '928', 1994, 'L93-12');
insert into Cars (Brand, Model, Year, Regnumber) values ('Isuzu', 'Axiom', 2004, 'F73-26');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', 'V8', 1991, 'K95-62');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lincoln', 'Aviator', 2004, 'U35-27');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', 'Bonneville', 1988, 'N26-44');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lincoln', 'Continental Mark VII', 1986, 'Z96-56');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', '4Runner', 2006, 'D17-71');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'RAV4', 2012, 'M23-16');
insert into Cars (Brand, Model, Year, Regnumber) values ('Land Rover', 'Discovery', 1998, 'E51-43');
insert into Cars (Brand, Model, Year, Regnumber) values ('Cadillac', 'Seville', 1999, 'S34-27');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', 'SLK-Class', 1999, 'Y58-71');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Suburban 2500', 2011, 'F22-26');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Avalanche 2500', 2003, 'P58-46');
insert into Cars (Brand, Model, Year, Regnumber) values ('Acura', 'Integra', 1995, 'K42-89');
insert into Cars (Brand, Model, Year, Regnumber) values ('Nissan', 'GT-R', 2009, 'B44-59');
insert into Cars (Brand, Model, Year, Regnumber) values ('Buick', 'Regal', 2011, 'D79-34');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', 'Bonneville', 1992, 'E94-93');
insert into Cars (Brand, Model, Year, Regnumber) values ('Saab', '9000', 1987, 'L86-45');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Suburban 2500', 1992, 'E58-52');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Crown Victoria', 2007, 'R12-35');
insert into Cars (Brand, Model, Year, Regnumber) values ('BMW', '6 Series', 2006, 'Z85-48');
insert into Cars (Brand, Model, Year, Regnumber) values ('Maybach', '62', 2004, 'Z24-38');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Econoline E150', 1997, 'K79-14');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Aerostar', 1991, 'H56-44');
insert into Cars (Brand, Model, Year, Regnumber) values ('Maserati', 'Quattroporte', 1984, 'K76-26');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Thunderbird', 1955, 'Z25-88');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Avalon', 1996, 'W13-13');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', 'MPV', 2005, 'X69-42');
insert into Cars (Brand, Model, Year, Regnumber) values ('Infiniti', 'M', 2009, 'Z11-89');
insert into Cars (Brand, Model, Year, Regnumber) values ('Plymouth', 'Breeze', 1996, 'W66-41');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', 'MX-5', 1995, 'X71-82');
insert into Cars (Brand, Model, Year, Regnumber) values ('BMW', '7 Series', 2001, 'D65-52');
insert into Cars (Brand, Model, Year, Regnumber) values ('Land Rover', 'Discovery', 2000, 'J29-89');
insert into Cars (Brand, Model, Year, Regnumber) values ('Rolls-Royce', 'Phantom', 2007, 'B27-42');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Xtra', 1992, 'Z92-65');
insert into Cars (Brand, Model, Year, Regnumber) values ('Nissan', 'Cube', 2009, 'G13-18');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Express 2500', 1998, 'M23-16');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'Fox', 1988, 'F28-37');
insert into Cars (Brand, Model, Year, Regnumber) values ('Subaru', 'Justy', 1994, 'U29-14');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Express 3500', 2006, 'V31-14');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ferrari', 'California', 2010, 'H98-19');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'E-Series', 2006, 'D62-92');
insert into Cars (Brand, Model, Year, Regnumber) values ('BMW', 'M6', 2009, 'N33-38');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', '5000S', 1987, 'D91-32');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', 'Firebird', 1990, 'M53-15');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'E-350 Super Duty Van', 2006, 'B24-68');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', '626', 1986, 'J47-74');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'D350', 1992, 'W58-95');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chrysler', 'Town & Country', 2007, 'P87-64');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', 'Miata MX-5', 2004, 'K59-29');
insert into Cars (Brand, Model, Year, Regnumber) values ('Nissan', 'Armada', 2008, 'T93-22');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Dakota', 1994, 'X21-53');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', 'V8', 1990, 'Z85-48');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Ram Van B250', 1993, 'H81-49');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volvo', 'V70', 1999, 'S73-92');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Lumina', 1994, 'I92-86');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'GTI', 2004, 'J11-79');
insert into Cars (Brand, Model, Year, Regnumber) values ('Subaru', 'Legacy', 2001, 'M73-98');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Mirage', 1992, 'Q81-25');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lamborghini', 'Murciélago', 2005, 'M54-68');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Escape', 2005, 'B54-87');
insert into Cars (Brand, Model, Year, Regnumber) values ('Suzuki', 'Esteem', 2002, 'R36-91');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Mirage', 1989, 'U35-27');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Explorer', 1994, 'S17-62');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Explorer Sport', 2001, 'N97-58');
insert into Cars (Brand, Model, Year, Regnumber) values ('Hyundai', 'Azera', 2011, 'Q75-13');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', 'Sprinter', 2011, 'J88-89');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', 'Firefly', 1985, 'U22-58');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chrysler', 'Concorde', 1999, 'P57-61');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'Cabriolet', 1989, 'U44-49');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'Rabbit', 2008, 'X45-89');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Avalon', 1996, 'G14-13');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volvo', 'C30', 2012, 'S56-62');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Camry Hybrid', 2010, 'L15-72');
insert into Cars (Brand, Model, Year, Regnumber) values ('Acura', 'RSX', 2004, 'T82-68');
insert into Cars (Brand, Model, Year, Regnumber) values ('Jaguar', 'XK', 2008, 'Y93-44');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lexus', 'IS F', 2008, 'V57-21');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Sierra 2500', 1999, 'F92-24');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'EXP', 1984, 'S71-43');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lincoln', 'MKZ', 2011, 'K25-68');
insert into Cars (Brand, Model, Year, Regnumber) values ('Subaru', 'Legacy', 1991, 'K31-12');
insert into Cars (Brand, Model, Year, Regnumber) values ('Nissan', 'Murano', 2004, 'J47-74');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Suburban 1500', 2002, 'J24-95');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Suburban 1500', 2006, 'P15-77');
insert into Cars (Brand, Model, Year, Regnumber) values ('Subaru', 'Leone', 1988, 'E28-76');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'Jetta III', 1994, 'L58-87');
insert into Cars (Brand, Model, Year, Regnumber) values ('Cadillac', 'Eldorado', 1997, 'Z18-97');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Colorado', 2011, 'K64-48');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Ram 2500', 2009, 'K15-93');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', 'SLK-Class', 2011, 'J95-79');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Corvette', 2000, 'G69-51');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Camry', 2009, 'Y25-72');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Ranger', 2003, 'R25-41');
insert into Cars (Brand, Model, Year, Regnumber) values ('Nissan', 'Pathfinder', 1999, 'Q34-37');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', '4000s Quattro', 1986, 'D79-17');
insert into Cars (Brand, Model, Year, Regnumber) values ('Honda', 'del Sol', 1994, 'K14-23');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Crown Victoria', 1998, 'Z75-25');
insert into Cars (Brand, Model, Year, Regnumber) values ('Honda', 'Ridgeline', 2009, 'W92-39');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Omni', 1978, 'I49-11');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volvo', 'C70', 1998, 'E28-76');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Sierra 1500', 2010, 'B55-18');
insert into Cars (Brand, Model, Year, Regnumber) values ('Aston Martin', 'Vantage', 2010, 'X98-57');
insert into Cars (Brand, Model, Year, Regnumber) values ('Infiniti', 'IPL G', 2012, 'P35-66');
insert into Cars (Brand, Model, Year, Regnumber) values ('Isuzu', 'Ascender', 2003, 'K64-48');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', 'Trans Sport', 1990, 'W39-75');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Durango', 2003, 'F63-15');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lexus', 'GS', 2005, 'A31-94');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Solara', 2004, 'O31-18');
insert into Cars (Brand, Model, Year, Regnumber) values ('Nissan', 'Altima', 2009, 'Y62-52');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Dakota', 2003, 'M71-96');
insert into Cars (Brand, Model, Year, Regnumber) values ('Cadillac', 'CTS', 2010, 'S61-37');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', 'CLK-Class', 2000, 'Q32-29');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', 'G-Class', 2012, 'W39-75');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Expo', 1995, 'B49-13');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Celica', 2004, 'M86-22');
insert into Cars (Brand, Model, Year, Regnumber) values ('Plymouth', 'Grand Voyager', 1992, 'W19-28');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Yukon XL 1500', 2011, 'N59-33');
insert into Cars (Brand, Model, Year, Regnumber) values ('BMW', 'X3', 2007, 'M23-16');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Tacoma', 1998, 'U93-93');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'Golf', 2003, 'D91-21');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', '626', 1998, 'Z89-73');
insert into Cars (Brand, Model, Year, Regnumber) values ('Infiniti', 'I', 1996, 'U35-27');
insert into Cars (Brand, Model, Year, Regnumber) values ('Subaru', 'Tribeca', 2010, 'I65-52');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Sonoma', 1997, 'W18-46');
insert into Cars (Brand, Model, Year, Regnumber) values ('Buick', 'Century', 1999, 'N57-11');
insert into Cars (Brand, Model, Year, Regnumber) values ('Plymouth', 'Prowler', 1997, 'C48-88');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Galant', 1990, 'K64-48');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', 'A5', 2009, 'B49-13');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Dakota', 1998, 'W65-26');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'F250', 2012, 'Q75-24');
insert into Cars (Brand, Model, Year, Regnumber) values ('Nissan', '350Z', 2009, 'A39-34');
insert into Cars (Brand, Model, Year, Regnumber) values ('BMW', 'X6 M', 2010, 'B62-28');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Impala SS', 1995, 'U23-82');
insert into Cars (Brand, Model, Year, Regnumber) values ('Hyundai', 'Elantra', 1995, 'S18-55');
insert into Cars (Brand, Model, Year, Regnumber) values ('Hyundai', 'Elantra', 2004, 'V15-97');
insert into Cars (Brand, Model, Year, Regnumber) values ('Honda', 'CR-V', 2003, 'B75-64');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Tempo', 1984, 'I42-53');
insert into Cars (Brand, Model, Year, Regnumber) values ('Nissan', 'Altima', 1999, 'P29-43');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', 'SL-Class', 1986, 'N75-13');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'F-Series Super Duty', 2011, 'R27-89');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lincoln', 'Town Cars', 1986, 'T95-53');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', 'Fiero', 1986, 'R17-87');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Sierra 2500', 2000, 'P19-46');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Freestyle', 2005, 'F91-98');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Pajero', 2001, 'Y45-59');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Mustang', 1991, 'G69-51');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Mustang', 1999, 'V15-38');
insert into Cars (Brand, Model, Year, Regnumber) values ('Infiniti', 'Q', 2003, 'Q33-78');
insert into Cars (Brand, Model, Year, Regnumber) values ('Nissan', 'Xterra', 2010, 'Y62-52');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Fairlane', 1965, 'S29-64');
insert into Cars (Brand, Model, Year, Regnumber) values ('Oldsmobile', 'Silhouette', 1998, 'U68-57');
insert into Cars (Brand, Model, Year, Regnumber) values ('Cadillac', 'CTS-V', 2012, 'T32-67');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Freestar', 2007, 'E72-99');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', 'A3', 2012, 'V32-71');
insert into Cars (Brand, Model, Year, Regnumber) values ('Subaru', 'Tribeca', 2009, 'A78-32');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Thunderbird', 1990, 'R73-84');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', 'RX-8', 2009, 'J47-74');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'RAV4', 1999, 'X85-35');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'Rabbit', 2009, 'H55-88');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Contour', 1995, 'N12-29');
insert into Cars (Brand, Model, Year, Regnumber) values ('Buick', 'Park Avenue', 2003, 'R27-89');
insert into Cars (Brand, Model, Year, Regnumber) values ('Buick', 'Lucerne', 2006, 'I92-86');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Camry', 2007, 'T23-22');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Envoy', 2002, 'J28-74');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Mirage', 1985, 'N26-12');
insert into Cars (Brand, Model, Year, Regnumber) values ('Suzuki', 'SJ 410', 1984, 'L67-48');
insert into Cars (Brand, Model, Year, Regnumber) values ('Infiniti', 'G', 1992, 'U71-55');
insert into Cars (Brand, Model, Year, Regnumber) values ('Isuzu', 'Trooper', 1993, 'Q33-78');
insert into Cars (Brand, Model, Year, Regnumber) values ('Subaru', 'SVX', 1997, 'R39-15');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Yukon', 1993, 'O39-92');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'F350', 2001, 'Q88-17');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Econoline E150', 1996, 'E51-99');
insert into Cars (Brand, Model, Year, Regnumber) values ('Porsche', '911', 2001, 'A12-63');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Express', 2008, 'E36-25');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', '1500 Club Coupe', 1996, 'K91-57');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'F250', 2001, 'Q17-18');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Matrix', 2012, 'V29-21');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', 'Grand Prix', 1991, 'O57-45');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Crown Victoria', 2006, 'Z92-65');
insert into Cars (Brand, Model, Year, Regnumber) values ('Subaru', 'Legacy', 2004, 'H44-43');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Sportvan G20', 1993, 'B13-64');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Dakota', 2000, 'B66-58');
insert into Cars (Brand, Model, Year, Regnumber) values ('Buick', 'Regal', 1992, 'T23-12');
insert into Cars (Brand, Model, Year, Regnumber) values ('Suzuki', 'Grand Vitara', 2000, 'J69-18');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volvo', 'C70', 2009, 'N57-11');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Highlander Hybrid', 2007, 'Q75-75');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lincoln', 'LS', 2000, 'J85-53');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Excursion', 2001, 'W76-38');
insert into Cars (Brand, Model, Year, Regnumber) values ('Smart', 'Fortwo', 2008, 'F85-18');
insert into Cars (Brand, Model, Year, Regnumber) values ('Acura', 'RL', 2001, 'Z75-25');
insert into Cars (Brand, Model, Year, Regnumber) values ('Cadillac', 'Catera', 1998, 'H19-72');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Monte Carslo', 2006, 'I18-49');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', 'Coupe Quattro', 1991, 'K64-13');
insert into Cars (Brand, Model, Year, Regnumber) values ('Honda', 'Odyssey', 2008, 'S53-62');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chrysler', 'LHS', 1996, 'Q88-47');
insert into Cars (Brand, Model, Year, Regnumber) values ('MINI', 'Cooper', 2004, 'F36-44');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lincoln', 'Town Cars', 2011, 'P52-55');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Suburban 1500', 2001, 'F28-66');
insert into Cars (Brand, Model, Year, Regnumber) values ('Subaru', 'Legacy', 2010, 'R25-41');
insert into Cars (Brand, Model, Year, Regnumber) values ('Hyundai', 'XG350', 2002, 'A86-61');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', '929', 1993, 'Q78-81');
insert into Cars (Brand, Model, Year, Regnumber) values ('Kia', 'Forte', 2011, 'V49-14');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Avalanche 2500', 2005, 'Y99-21');
insert into Cars (Brand, Model, Year, Regnumber) values ('Nissan', 'Xterra', 2001, 'O59-31');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', 'A6', 1997, 'E72-99');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Montero', 1999, 'Y94-43');
insert into Cars (Brand, Model, Year, Regnumber) values ('Isuzu', 'Rodeo', 2003, 'P84-57');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', 'Firebird', 1998, 'L77-84');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volvo', 'S80', 2007, 'V41-21');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Intrepid', 2002, 'K54-79');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Suburban 1500', 2007, 'W29-58');
insert into Cars (Brand, Model, Year, Regnumber) values ('Suzuki', 'SJ', 1988, 'T16-98');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Montero', 1999, 'O55-28');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Tundra', 2009, 'F94-55');
insert into Cars (Brand, Model, Year, Regnumber) values ('Plymouth', 'Neon', 2000, 'C83-65');
insert into Cars (Brand, Model, Year, Regnumber) values ('Subaru', 'Alcyone SVX', 1996, 'T83-33');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Econoline E150', 2000, 'Q41-15');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Thunderbird', 1955, 'D12-27');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lincoln', 'Town Cars', 2005, 'T93-22');
insert into Cars (Brand, Model, Year, Regnumber) values ('Honda', 'Civic', 2008, 'F31-44');
insert into Cars (Brand, Model, Year, Regnumber) values ('Infiniti', 'FX', 2003, 'D27-47');
insert into Cars (Brand, Model, Year, Regnumber) values ('Jaguar', 'X-Type', 2008, 'C53-29');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'E-Series', 2011, 'B47-33');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Envoy XL', 2006, 'Z99-96');
insert into Cars (Brand, Model, Year, Regnumber) values ('Cadillac', 'Eldorado', 1997, 'J88-89');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', 'Navajo', 1991, 'D46-59');
insert into Cars (Brand, Model, Year, Regnumber) values ('BMW', '645', 2005, 'E65-83');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lexus', 'LS', 2011, 'Y16-34');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', '3500', 1998, 'W39-76');
insert into Cars (Brand, Model, Year, Regnumber) values ('Kia', 'Sedona', 2004, 'Q75-13');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Thunderbird', 1997, 'X59-93');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lincoln', 'Continental Mark VII', 1988, 'E56-41');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Sierra 3500', 2010, 'C55-75');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Neon', 1998, 'V87-11');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Express 2500', 2008, 'D79-34');
insert into Cars (Brand, Model, Year, Regnumber) values ('Maserati', 'Karif', 1990, 'Y62-78');
insert into Cars (Brand, Model, Year, Regnumber) values ('Saturn', 'S-Series', 1999, 'O85-28');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Celica', 1999, 'O17-27');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Crown Victoria', 1992, 'E51-93');
insert into Cars (Brand, Model, Year, Regnumber) values ('Jeep', 'Patriot', 2008, 'K17-44');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', 'Mazda6', 2013, 'Y33-16');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'LTD', 1984, 'X59-93');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', '3500 Club Coupe', 1993, 'W78-88');
insert into Cars (Brand, Model, Year, Regnumber) values ('Kia', 'Rio', 2005, 'D12-27');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', 'Trans Sport', 1996, 'H63-22');
insert into Cars (Brand, Model, Year, Regnumber) values ('Isuzu', 'Oasis', 1997, 'S54-82');
insert into Cars (Brand, Model, Year, Regnumber) values ('Hyundai', 'Elantra', 1997, 'L31-36');
insert into Cars (Brand, Model, Year, Regnumber) values ('Suzuki', 'Daewoo Lacetti', 2006, 'Q75-75');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lexus', 'IS', 2010, 'V72-28');
insert into Cars (Brand, Model, Year, Regnumber) values ('Maybach', '62', 2008, 'K49-35');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'F350', 2003, 'G79-64');
insert into Cars (Brand, Model, Year, Regnumber) values ('Infiniti', 'FX', 2012, 'A56-41');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Yukon', 2012, 'M71-96');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volvo', 'S60', 2008, 'F22-54');
insert into Cars (Brand, Model, Year, Regnumber) values ('Cadillac', 'STS', 2006, 'S29-64');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Econoline E150', 1993, 'E58-28');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Corsica', 1996, 'Y51-16');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Expedition', 2002, 'D53-14');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Fairlane', 1965, 'Y27-96');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Ranger', 1993, 'B44-59');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Ram 1500 Club', 2000, 'E21-87');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercury', 'Marquis', 1986, 'K98-92');
insert into Cars (Brand, Model, Year, Regnumber) values ('Porsche', '968', 1993, 'D91-21');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Mustang', 1965, 'Y68-71');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Avalon', 2002, 'W65-78');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Ramcharger', 1993, 'Q51-77');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Beretta', 1996, 'B66-58');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Diamante', 1992, 'J49-23');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Taurus', 1986, 'P84-57');
insert into Cars (Brand, Model, Year, Regnumber) values ('Nissan', 'Titan', 2006, 'U47-98');
insert into Cars (Brand, Model, Year, Regnumber) values ('BMW', 'M5', 2002, 'H11-57');
insert into Cars (Brand, Model, Year, Regnumber) values ('Infiniti', 'I', 1996, 'B63-55');
insert into Cars (Brand, Model, Year, Regnumber) values ('Hyundai', 'Entourage', 2008, 'H36-62');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ferrari', '430 Scuderia', 2008, 'T95-99');
insert into Cars (Brand, Model, Year, Regnumber) values ('Saab', '9-7X', 2007, 'R32-45');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chrysler', 'Sebring', 1999, 'L21-53');
insert into Cars (Brand, Model, Year, Regnumber) values ('Buick', 'Coachbuilder', 1993, 'J99-54');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Explorer', 2008, 'P17-45');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', 'Bonneville', 1968, 'K72-74');
insert into Cars (Brand, Model, Year, Regnumber) values ('Nissan', 'Frontier', 2000, 'Q37-32');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', 'E-Class', 1997, 'X85-35');
insert into Cars (Brand, Model, Year, Regnumber) values ('Hyundai', 'Santa Fe', 2006, 'T23-12');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'GTI', 1998, 'K41-24');
insert into Cars (Brand, Model, Year, Regnumber) values ('Daewoo', 'Lanos', 2000, 'W29-58');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Montero', 1992, 'Z36-76');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'Touareg', 2004, 'M93-38');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', 'A8', 2010, 'V69-44');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Courier', 1986, 'V32-71');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Corvette', 2009, 'U71-55');
insert into Cars (Brand, Model, Year, Regnumber) values ('Land Rover', 'Range Rover', 2010, 'G69-51');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chrysler', 'Town & Country', 2007, 'O17-27');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Yaris', 2009, 'Y26-17');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lamborghini', 'Countach', 1990, 'V15-45');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Galant', 1985, 'T16-98');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', 'B-Series', 1994, 'C39-43');
insert into Cars (Brand, Model, Year, Regnumber) values ('Suzuki', 'Daewoo Lacetti', 2008, 'U68-87');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Matrix', 2012, 'V41-96');
insert into Cars (Brand, Model, Year, Regnumber) values ('Subaru', 'Forester', 2008, 'I35-72');
insert into Cars (Brand, Model, Year, Regnumber) values ('Buick', 'LeSabre', 1990, 'Min enhet I går tis 22:57  Du laddade upp 2 objekt Text randomRegNums.txt Okänd filtyp MOCK_DATA (2).json Förra veckan fre 22:29  Du har skapat 14 objekt i Google Drive-mapp Google Foto Bild IMG_20181012_222836.jpg Bild IMG_20181012_222837.jpg Bild IMG_20181012_222830.jpg Bild IMG_20181012_222811.jpg Bild IMG_20181012_222813.jpg Bild IMG_20181010_194630.jpg 9 okt.  Du har skapat 9 objekt i Google Drive-mapp Google Foto Bild IMG_20181009_200859.jpg Bild IMG_20181009_200900.jpg Bild IMG_20181009_200855.jpg Bild Screenshot_20181008-001630.jpg Bild IMG_20180926_125143.jpg Bild IMG_20180928_181213.jpg Tidigare den här månaden 5 okt.  Duhar flyttat ett objekt till papperskorgen Bild IMG_20180917_140731.jpg 5 okt.  Du har skapat 2 objekt i Google Drive-mapp Google Foto Bild IMG_20181005_105046.jpg Bild Screenshot_20181002-212133.jpg Föregående månad 30 sep.  Du har skapat ett objekt i Google Drive-mapp Google Foto Bild IMG_20180929_141310__01.jpg 29 sep.  Du har redigerat ett objekt Google Dokument Laptops 29 sep.  Du har delat ett objekt Google Dokument Laptops Får visa Alla med länken 29 sep.  Du har redigerat ett objekt Google Dokument Laptops 29 sep.  Du har skapat ett objekt Google Dokument Laptops 29 sep.  Du har skapat ett objekt i Google Drive-mapp Google Foto Bild IMG_20180929_141310.jpg 25 sep.  Du har redigerat ett objekt Google Dokument Namnlöst dokument 23 sep.  Du har skapat ett objekt Google Dokument Namnlöst dokument 21 sep.  Du har skapat 6 objekt i Google Drive-mapp Google Foto Bild IMG_20180920_195751.jpg Bild IMG_20180920_194407.jpg Bild Screenshot_20180920-122443.jpg Bild Screenshot_20180920-122410.jpg Bild Screenshot_20180920-122429.jpg Bild Screenshot_20180919-222816.jpg 17 sep.  Du har skapat 16 objekt i Google Drive-mapp Google Foto Bild IMG_20180917_140731.jpg Bild IMG_20180917_083524__01.jpg Bild IMG_20180917_083524.jpg Bild IMG_20180914_232201.jpg Bild IMG_20180914_232206.jpg Bild IMG_20180914_232153.jpg 12 sep.  Du laddade upp ett objekt PDF epdf.tips_calculus-a-complete-course-plus-mymathlab-global-2.pdf 10 sep.  Duhar flyttat 2 objekt till papperskorgen Bild Screenshot_20180909-183332.jpg Google Dokument Namnlöst dokument 10 sep.  Du har skapat ett objekt Google Dokument Namnlöst dokument 10 sep.  Du har skapat 4 objekt i Google Drive-mapp Google Foto Bild Screenshot_20180909-183332.jpg Bild IMG_20180908_234156.jpg Bild IMG_20180905_135819.jpg Bild Screenshot_20180903-063653.jpg 3 sep.  Duhar flyttat ett objekt till papperskorgen XML countries.xml J24-83');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', 'Firebird', 1989, 'A48-71');
insert into Cars (Brand, Model, Year, Regnumber) values ('Suzuki', 'XL-7', 2008, 'J95-79');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Galant', 1997, 'A11-47');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Avenger', 1999, 'M86-15');
insert into Cars (Brand, Model, Year, Regnumber) values ('Suzuki', 'Equator', 2011, 'W75-19');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Courier', 1987, 'P71-51');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', '4Runner', 2002, 'G95-73');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'Phaeton', 2006, 'R25-41');
insert into Cars (Brand, Model, Year, Regnumber) values ('Oldsmobile', '98', 1993, 'A82-39');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', 'Mazda6', 2012, 'L18-91');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lexus', 'IS F', 2011, 'Y22-44');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', 'Grand Prix', 1968, 'M64-59');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', 'B-Series', 2009, 'Z75-28');
insert into Cars (Brand, Model, Year, Regnumber) values ('Bentley', 'Mulsanne', 2011, 'W89-64');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ferrari', '612 Scaglietti', 2010, 'B76-72');
insert into Cars (Brand, Model, Year, Regnumber) values ('Porsche', '911', 1989, 'T19-63');
insert into Cars (Brand, Model, Year, Regnumber) values ('Jeep', 'Wrangler', 2010, 'V51-85');
insert into Cars (Brand, Model, Year, Regnumber) values ('Kia', 'Carsens', 2009, 'O25-76');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Volt', 2012, 'E76-85');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Tacoma', 2003, 'U34-53');
insert into Cars (Brand, Model, Year, Regnumber) values ('Buick', 'Regal', 2000, 'T84-94');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lexus', 'LS', 2004, 'D53-14');
insert into Cars (Brand, Model, Year, Regnumber) values ('Porsche', '911', 1998, 'E51-93');
insert into Cars (Brand, Model, Year, Regnumber) values ('Nissan', 'Pathfinder', 1992, 'Q59-63');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', 'Solstice', 2008, 'S17-77');
insert into Cars (Brand, Model, Year, Regnumber) values ('BMW', '6 Series', 2006, 'Q17-85');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Acadia', 2007, 'V99-78');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'Touareg', 2009, 'F91-98');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Avalanche', 2012, 'L97-32');
insert into Cars (Brand, Model, Year, Regnumber) values ('Oldsmobile', 'Intrigue', 2001, 'M98-11');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Viper', 1993, 'T18-33');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', 'S-Class', 1994, 'H42-71');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Mirage', 1993, 'M18-74');
insert into Cars (Brand, Model, Year, Regnumber) values ('Land Rover', 'Discovery', 2011, 'R34-98');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Suburban 1500', 2004, 'E94-93');
insert into Cars (Brand, Model, Year, Regnumber) values ('Porsche', 'Carsrera GT', 2004, 'V41-21');
insert into Cars (Brand, Model, Year, Regnumber) values ('Citroën', 'SM', 1972, 'H56-73');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chrysler', 'Crossfire Roadster', 2006, 'T56-14');
insert into Cars (Brand, Model, Year, Regnumber) values ('Land Rover', 'Freelander', 2001, 'E71-88');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'F150', 2000, 'A57-33');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', 'A8', 2010, 'U35-27');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Yukon XL 2500', 2007, 'H63-22');
insert into Cars (Brand, Model, Year, Regnumber) values ('Honda', 'Fit', 2008, 'Z72-89');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chrysler', 'Pacifica', 2004, 'T17-45');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Sierra 2500', 2001, 'L97-11');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lincoln', 'LS', 2005, 'I89-85');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Traverse', 2012, 'I99-19');
insert into Cars (Brand, Model, Year, Regnumber) values ('Honda', 'Prelude', 1986, 'S79-13');
insert into Cars (Brand, Model, Year, Regnumber) values ('Suzuki', 'Daewoo Magnus', 2004, 'T89-59');
insert into Cars (Brand, Model, Year, Regnumber) values ('Geo', 'Prizm', 1994, 'F79-65');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', '3500', 1999, 'C48-88');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lincoln', 'Continental', 2001, 'U93-21');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chrysler', 'LHS', 1995, 'R78-45');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Prizm', 2002, 'H72-43');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Matrix', 2007, 'Q15-33');
insert into Cars (Brand, Model, Year, Regnumber) values ('BMW', '7 Series', 1998, 'N66-75');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Celica', 1993, 'K76-26');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Probe', 1989, 'Z36-76');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Ram 1500 Club', 1995, 'C48-88');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Eclipse', 1991, 'D27-47');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Rally Wagon 3500', 1992, 'O54-29');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', 'S-Class', 2005, 'S42-94');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Express', 2006, 'W58-95');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercury', 'Topaz', 1994, 'D65-52');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', 'B-Series', 1994, 'I35-72');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Sequoia', 2009, 'J18-73');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Neon', 1998, 'S27-12');
insert into Cars (Brand, Model, Year, Regnumber) values ('BMW', '3 Series', 1994, 'Q78-61');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Ramcharger', 1993, 'M69-33');
insert into Cars (Brand, Model, Year, Regnumber) values ('Honda', 'Fit', 2008, 'W89-64');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Tempo', 1990, 'O16-26');
insert into Cars (Brand, Model, Year, Regnumber) values ('Kia', 'Spectra', 2008, 'F41-56');
insert into Cars (Brand, Model, Year, Regnumber) values ('Buick', 'Skylark', 1997, 'Q12-37');
insert into Cars (Brand, Model, Year, Regnumber) values ('Subaru', 'Legacy', 2012, 'W55-84');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Explorer Sport Trac', 2008, 'J18-73');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Durango', 2002, 'Q52-37');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Corolla', 2001, 'A11-47');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Challenger', 1997, 'G19-86');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Colt', 1994, 'V93-17');
insert into Cars (Brand, Model, Year, Regnumber) values ('Acura', 'NSX', 2001, 'V18-27');
insert into Cars (Brand, Model, Year, Regnumber) values ('Aston Martin', 'Vantage', 2006, 'A92-88');
insert into Cars (Brand, Model, Year, Regnumber) values ('Acura', 'TL', 1997, 'V72-28');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercury', 'Mystique', 1998, 'A62-75');
insert into Cars (Brand, Model, Year, Regnumber) values ('Nissan', 'Frontier', 2003, 'C15-31');
insert into Cars (Brand, Model, Year, Regnumber) values ('Jaguar', 'XJ Series', 2001, 'Z72-89');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', 'C-Class', 2000, 'U22-58');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Crown Victoria', 1998, 'E56-41');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Sportvan G30', 1992, 'N26-44');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Durango', 2006, 'C22-85');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Probe', 1997, 'G67-85');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lexus', 'LX', 1996, 'J29-89');
insert into Cars (Brand, Model, Year, Regnumber) values ('Rolls-Royce', 'Phantom', 2007, 'W75-19');
insert into Cars (Brand, Model, Year, Regnumber) values ('Cadillac', 'Eldorado', 1993, 'C15-32');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lamborghini', 'Gallardo', 2012, 'U22-58');
insert into Cars (Brand, Model, Year, Regnumber) values ('Suzuki', 'Swift', 2001, 'E51-93');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Taurus', 2009, 'Y91-87');
insert into Cars (Brand, Model, Year, Regnumber) values ('Suzuki', 'Daewoo Lacetti', 2006, 'R72-48');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', 'Grand Prix', 1989, 'A97-43');
insert into Cars (Brand, Model, Year, Regnumber) values ('Oldsmobile', '88', 1993, 'E63-11');
insert into Cars (Brand, Model, Year, Regnumber) values ('Plymouth', 'Grand Voyager', 1996, 'L46-84');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Highlander', 2009, 'H43-59');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', 'A8', 2011, 'W86-65');
insert into Cars (Brand, Model, Year, Regnumber) values ('Saturn', 'Ion', 2007, 'C92-49');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'Golf', 1991, 'W58-28');
insert into Cars (Brand, Model, Year, Regnumber) values ('Scion', 'xD', 2008, 'A66-19');
insert into Cars (Brand, Model, Year, Regnumber) values ('Nissan', 'Frontier', 2004, 'X57-84');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Windstar', 2003, 'S78-36');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', 'E-Class', 2008, 'P57-61');
insert into Cars (Brand, Model, Year, Regnumber) values ('Bentley', 'Continental GTC', 2011, 'P81-38');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lexus', 'LS', 2012, 'S47-75');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Impala', 2000, 'F26-27');
insert into Cars (Brand, Model, Year, Regnumber) values ('Infiniti', 'M', 2003, 'Z89-73');
insert into Cars (Brand, Model, Year, Regnumber) values ('Cadillac', 'Seville', 1992, 'K74-98');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'LTD Crown Victoria', 1988, 'G11-28');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lexus', 'ES', 2010, 'H23-29');
insert into Cars (Brand, Model, Year, Regnumber) values ('Buick', 'Skyhawk', 1989, 'J92-45');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', 'Grand Prix', 1964, 'M54-68');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', 'S-Class', 2003, 'W58-95');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'MR2', 1992, 'O51-39');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', 'Mazda6', 2011, 'Y16-34');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'E250', 2006, 'H63-22');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'Eurovan', 1997, 'F83-35');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', 'Firebird', 1999, 'U87-18');
insert into Cars (Brand, Model, Year, Regnumber) values ('Oldsmobile', 'Cutlass Cruiser', 1994, 'E51-43');
insert into Cars (Brand, Model, Year, Regnumber) values ('BMW', 'M3', 2009, 'B96-61');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chrysler', '300C', 2005, 'I24-48');
insert into Cars (Brand, Model, Year, Regnumber) values ('Hyundai', 'Genesis', 2012, 'G99-64');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Savana 1500', 2003, 'A12-63');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Galant', 1991, 'C48-88');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Yukon', 1992, 'Q88-47');
insert into Cars (Brand, Model, Year, Regnumber) values ('Plymouth', 'Voyager', 1992, 'U29-92');
insert into Cars (Brand, Model, Year, Regnumber) values ('Cadillac', 'Escalade EXT', 2002, 'P71-51');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Ram 3500', 1998, 'L99-32');
insert into Cars (Brand, Model, Year, Regnumber) values ('BMW', 'M3', 2005, 'V55-79');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'Cabriolet', 1999, 'D34-47');
insert into Cars (Brand, Model, Year, Regnumber) values ('BMW', 'M3', 1996, 'P43-36');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Envoy XL', 2003, 'L83-37');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Previa', 1997, 'S49-11');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', 'R8', 2008, 'Q88-47');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Bronco II', 1984, 'Z67-96');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Aerostar', 1989, 'U68-87');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Sienna', 2011, 'O61-38');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Savana 1500', 2007, 'G78-44');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercury', 'Mariner', 2006, 'A48-71');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volvo', 'C70', 2002, 'N27-27');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Avenger', 1997, 'R78-45');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Econoline E150', 1995, 'B59-92');
insert into Cars (Brand, Model, Year, Regnumber) values ('Aston Martin', 'V8 Vantage', 2009, 'C25-81');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Ram 1500', 2009, 'W99-89');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Chariot', 1989, 'V13-85');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Rally Wagon G3500', 1995, 'B63-55');
insert into Cars (Brand, Model, Year, Regnumber) values ('Acura', 'Legend', 1988, 'K59-29');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', '3500', 1996, 'M48-57');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lincoln', 'Navigator', 2001, 'C43-12');
insert into Cars (Brand, Model, Year, Regnumber) values ('Bentley', 'Continental', 2008, 'Z11-89');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', 'Grand Am', 1990, 'S51-13');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Torino', 1970, 'J95-79');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'Jetta', 1997, 'A15-85');
insert into Cars (Brand, Model, Year, Regnumber) values ('Cadillac', 'Fleetwood', 1993, 'O16-26');
insert into Cars (Brand, Model, Year, Regnumber) values ('Maserati', 'Coupe', 2006, 'T19-63');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Previa', 1993, 'K76-26');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Solara', 2005, 'G93-93');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lexus', 'LX', 2009, 'A56-41');
insert into Cars (Brand, Model, Year, Regnumber) values ('Nissan', 'Cube', 2012, 'Z89-94');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'TundraMax', 2007, 'B55-18');
insert into Cars (Brand, Model, Year, Regnumber) values ('Nissan', 'Murano', 2010, 'Z72-66');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'Passat', 2007, 'C83-65');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'Corrado', 1990, 'L56-21');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chrysler', 'LeBaron', 1992, 'O16-74');
insert into Cars (Brand, Model, Year, Regnumber) values ('Eagle', 'Summit', 1995, 'O21-99');
insert into Cars (Brand, Model, Year, Regnumber) values ('Cadillac', 'STS', 2010, 'C11-24');
insert into Cars (Brand, Model, Year, Regnumber) values ('Alfa Romeo', 'Spider', 1992, 'Q57-43');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', 'CLK-Class', 2007, 'M81-56');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Silverado 2500', 2000, 'W75-19');
insert into Cars (Brand, Model, Year, Regnumber) values ('MINI', 'Cooper', 2004, 'B54-81');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'GTI', 2001, 'S79-13');
insert into Cars (Brand, Model, Year, Regnumber) values ('Maybach', 'Landaulet', 2012, 'R27-89');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', 'Navajo', 1994, 'G99-18');
insert into Cars (Brand, Model, Year, Regnumber) values ('Acura', 'Vigor', 1992, 'D17-71');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', 'CLK-Class', 2006, 'L45-83');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Aerostar', 1996, 'R25-55');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'FJ Cruiser', 2011, 'O11-87');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'F250', 1995, 'P17-45');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', 'SLR McLaren', 2009, 'M53-15');
insert into Cars (Brand, Model, Year, Regnumber) values ('Oldsmobile', 'Silhouette', 2004, 'S24-54');
insert into Cars (Brand, Model, Year, Regnumber) values ('Honda', 'Civic', 1997, 'S88-65');
insert into Cars (Brand, Model, Year, Regnumber) values ('Oldsmobile', 'Achieva', 1995, 'Z57-69');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Savana', 2009, 'W32-67');
insert into Cars (Brand, Model, Year, Regnumber) values ('Honda', 'Ridgeline', 2006, 'A92-88');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'GTO', 1997, 'W64-57');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Yukon', 1997, 'M24-75');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Venture', 1998, 'C83-35');
insert into Cars (Brand, Model, Year, Regnumber) values ('Honda', 'Passport', 1997, 'Y34-86');
insert into Cars (Brand, Model, Year, Regnumber) values ('Geo', 'Tracker', 1992, 'O19-43');
insert into Cars (Brand, Model, Year, Regnumber) values ('Jeep', 'Grand Cherokee', 2002, 'Q15-33');
insert into Cars (Brand, Model, Year, Regnumber) values ('BMW', '7 Series', 2006, 'A83-32');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercury', 'Villager', 1993, 'Y34-86');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Escort', 1987, 'W19-24');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lexus', 'RX', 2006, 'Q34-37');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Escape', 2011, 'P58-46');
insert into Cars (Brand, Model, Year, Regnumber) values ('Geo', 'Metro', 1997, 'D62-92');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', 'Bonneville', 1990, 'C15-72');
insert into Cars (Brand, Model, Year, Regnumber) values ('Aptera', '2e', 2009, 'Y65-43');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', 'Q5', 2009, 'Q36-97');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'Passat', 1999, 'X26-52');
insert into Cars (Brand, Model, Year, Regnumber) values ('Acura', 'TL', 1999, 'Z34-45');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Avalon', 2003, 'S29-64');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Taurus', 2006, 'E39-57');
insert into Cars (Brand, Model, Year, Regnumber) values ('Porsche', 'Cayenne', 2013, 'O17-27');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Dakota Club', 2001, 'V34-73');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Truck Xtracab SR5', 1989, 'I95-22');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', 'Montana', 2006, 'S54-92');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Ram 1500 Club', 2001, 'O54-65');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', '1500 Club Coupe', 1995, 'L53-93');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', 'Grand Prix', 2004, 'W54-72');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lexus', 'SC', 2006, 'J22-32');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Stealth', 1993, 'Z46-31');
insert into Cars (Brand, Model, Year, Regnumber) values ('Eagle', 'Talon', 1990, 'X98-57');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Camry Hybrid', 2011, 'N17-11');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', 'CLK-Class', 1999, 'R32-45');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'EXP', 1985, 'F18-46');
insert into Cars (Brand, Model, Year, Regnumber) values ('Infiniti', 'QX56', 2012, 'H59-52');
insert into Cars (Brand, Model, Year, Regnumber) values ('Acura', 'Integra', 1996, 'Q17-18');
insert into Cars (Brand, Model, Year, Regnumber) values ('Kia', 'Sephia', 1998, 'U36-66');
insert into Cars (Brand, Model, Year, Regnumber) values ('BMW', 'M3', 1999, 'N33-38');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volvo', 'S80', 2010, 'Y27-96');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Outlander', 2012, 'L13-65');
insert into Cars (Brand, Model, Year, Regnumber) values ('Acura', 'Integra', 1994, 'F48-62');
insert into Cars (Brand, Model, Year, Regnumber) values ('Jeep', 'Commander', 2006, 'M64-53');
insert into Cars (Brand, Model, Year, Regnumber) values ('Rolls-Royce', 'Phantom', 2011, 'E38-16');
insert into Cars (Brand, Model, Year, Regnumber) values ('Honda', 'CR-V', 2009, 'Y93-44');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lincoln', 'Continental', 1992, 'D53-14');
insert into Cars (Brand, Model, Year, Regnumber) values ('Suzuki', 'Daewoo Lacetti', 2008, 'I86-55');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Explorer', 1995, 'V87-88');
insert into Cars (Brand, Model, Year, Regnumber) values ('Saturn', 'S-Series', 2002, 'L76-62');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Pajero', 1998, 'H49-76');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'G-Series 3500', 1998, 'K98-92');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercury', 'Cougar', 1967, 'Z43-75');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Tundra', 2008, 'G48-88');
insert into Cars (Brand, Model, Year, Regnumber) values ('Buick', 'LeSabre', 2002, 'C48-88');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lincoln', 'Continental', 1989, 'N92-66');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Matrix', 2010, 'S64-28');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Chariot', 1990, 'N19-97');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Suburban', 2009, 'V23-31');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Savana 2500', 1999, 'K49-73');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Blazer', 1996, 'C11-24');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Bronco', 1995, 'M21-17');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lamborghini', 'Gallardo', 2009, 'A14-72');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Silverado 2500', 2005, 'T99-35');
insert into Cars (Brand, Model, Year, Regnumber) values ('BMW', '325', 2006, 'K66-42');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Explorer Sport Trac', 2007, 'J85-18');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lincoln', 'Continental', 1991, 'I32-63');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Journey', 2010, 'F41-56');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ferrari', '612 Scaglietti', 2006, 'D85-28');
insert into Cars (Brand, Model, Year, Regnumber) values ('Subaru', 'Impreza', 2008, 'L82-42');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercury', 'Grand Marquis', 1993, 'Z43-75');
insert into Cars (Brand, Model, Year, Regnumber) values ('Subaru', 'Legacy', 2012, 'P33-21');
insert into Cars (Brand, Model, Year, Regnumber) values ('Buick', 'Skylark', 1997, 'R89-58');
insert into Cars (Brand, Model, Year, Regnumber) values ('Jeep', 'Grand Cherokee', 1997, 'C28-39');
insert into Cars (Brand, Model, Year, Regnumber) values ('Jeep', 'Commander', 2007, 'D34-47');
insert into Cars (Brand, Model, Year, Regnumber) values ('Hyundai', 'Santa Fe', 2009, 'H64-55');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Canyon', 2011, 'T71-73');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Malibu', 2010, 'J85-18');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chrysler', 'Town & Country', 2010, 'I42-27');
insert into Cars (Brand, Model, Year, Regnumber) values ('Buick', 'Roadmaster', 1993, 'U44-49');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Tacoma', 2004, 'Q57-93');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Savana 3500', 2004, 'U29-92');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Escape', 2009, 'Q92-53');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', 'Tribute', 2003, 'O54-29');
insert into Cars (Brand, Model, Year, Regnumber) values ('Porsche', '911', 1998, 'O76-21');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Cruze', 2011, 'H23-29');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volvo', 'XC60', 2011, 'L93-12');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', 'Tribute', 2009, 'U18-99');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'Golf', 1996, 'I69-27');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', 'Grand Prix', 1984, 'G15-27');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Sierra 3500', 2011, 'O31-18');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', 'Mazda3', 2010, 'P59-23');
insert into Cars (Brand, Model, Year, Regnumber) values ('Honda', 'Odyssey', 1998, 'Q84-26');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', 'Navajo', 1994, 'G91-75');
insert into Cars (Brand, Model, Year, Regnumber) values ('BMW', '5 Series', 1997, 'V38-39');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Silverado 3500', 2005, 'S24-54');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'F350', 2007, 'B85-59');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', 'A6', 2012, 'K49-73');
insert into Cars (Brand, Model, Year, Regnumber) values ('Hyundai', 'Scoupe', 1992, 'S49-11');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Excursion', 2001, 'Y83-13');
insert into Cars (Brand, Model, Year, Regnumber) values ('Acura', 'NSX', 2000, 'Z75-25');
insert into Cars (Brand, Model, Year, Regnumber) values ('Hyundai', 'Veracruz', 2008, 'V15-38');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Expedition EL', 2008, 'F91-98');
insert into Cars (Brand, Model, Year, Regnumber) values ('Hyundai', 'Entourage', 2008, 'O37-23');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volvo', 'V90', 1998, 'H56-61');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'Jetta', 1992, 'S73-92');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', 'LeMans', 1989, 'N33-38');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volvo', 'XC90', 2007, 'J92-45');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lexus', 'ES', 2003, 'N48-83');
insert into Cars (Brand, Model, Year, Regnumber) values ('Saturn', 'Ion', 2006, 'K95-62');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Caprice Classic', 1996, 'I69-27');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chrysler', 'PT Cruiser', 2009, 'C86-35');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Savana 1500', 1998, 'G48-88');
insert into Cars (Brand, Model, Year, Regnumber) values ('Kia', 'Rio', 2008, 'K49-29');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lotus', 'Elan', 1991, 'T84-94');
insert into Cars (Brand, Model, Year, Regnumber) values ('BMW', 'M6', 2010, 'X57-84');
insert into Cars (Brand, Model, Year, Regnumber) values ('Nissan', '350Z', 2007, 'J89-14');
insert into Cars (Brand, Model, Year, Regnumber) values ('Buick', 'Regal', 1986, 'W99-89');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mazda', 'CX-9', 2012, 'V87-11');
insert into Cars (Brand, Model, Year, Regnumber) values ('Rolls-Royce', 'Phantom', 2010, 'T36-27');
insert into Cars (Brand, Model, Year, Regnumber) values ('Nissan', 'Titan', 2012, 'B75-64');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'Eurovan', 1995, 'F54-26');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Precis', 1992, 'D49-32');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', 'Allroad', 2003, 'A31-77');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lexus', 'IS', 2011, 'W75-21');
insert into Cars (Brand, Model, Year, Regnumber) values ('Oldsmobile', 'Achieva', 1994, 'E58-28');
insert into Cars (Brand, Model, Year, Regnumber) values ('Cadillac', 'STS', 2006, 'K26-42');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Safari', 1997, 'T19-63');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Mustang', 1987, 'F84-61');
insert into Cars (Brand, Model, Year, Regnumber) values ('Honda', 'Pilot', 2006, 'F26-27');
insert into Cars (Brand, Model, Year, Regnumber) values ('Buick', 'Skyhawk', 1987, 'Q75-24');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'RAV4', 1998, 'L26-94');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Astro', 2000, 'I65-52');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'New Beetle', 2009, 'M48-57');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'F-Series', 1995, 'I42-53');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', 'E-Class', 2006, 'C73-52');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Sonoma', 1997, 'J85-53');
insert into Cars (Brand, Model, Year, Regnumber) values ('Subaru', 'Justy', 1993, 'V36-27');
insert into Cars (Brand, Model, Year, Regnumber) values ('Saturn', 'VUE', 2008, 'C16-44');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Classic', 2005, 'L56-92');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercury', 'Grand Marquis', 2009, 'H56-73');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Eclipse', 2007, 'Q88-47');
insert into Cars (Brand, Model, Year, Regnumber) values ('Audi', '100', 1990, 'L97-11');
insert into Cars (Brand, Model, Year, Regnumber) values ('Saab', '9-2X', 2006, 'T29-64');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Yukon XL 1500', 2013, 'V51-85');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Ram 3500 Club', 1997, 'B47-33');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volvo', 'V70', 2010, 'K23-86');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Savana 2500', 2001, 'S27-12');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Eclipse', 2005, 'D85-28');
insert into Cars (Brand, Model, Year, Regnumber) values ('BMW', '530', 2007, 'S53-62');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Fairlane', 1966, 'H56-73');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Savana 1500', 1999, 'P15-77');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', 'CLK-Class', 2004, 'G89-64');
insert into Cars (Brand, Model, Year, Regnumber) values ('Honda', 'Civic', 2007, 'T29-64');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Ram Van 2500', 2002, 'Q75-24');
insert into Cars (Brand, Model, Year, Regnumber) values ('Volkswagen', 'New Beetle', 2006, 'K17-44');
insert into Cars (Brand, Model, Year, Regnumber) values ('Porsche', '911', 2007, 'I58-94');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Traverse', 2011, 'L57-26');
insert into Cars (Brand, Model, Year, Regnumber) values ('Dodge', 'Ram 1500', 1998, 'U68-57');
insert into Cars (Brand, Model, Year, Regnumber) values ('Nissan', 'Sentra', 2007, 'X21-53');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', 'Solstice', 2007, 'Z89-73');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lincoln', 'MKZ', 2008, 'B85-59');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercury', 'Milan', 2009, 'B59-92');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Metro', 1998, 'Y33-66');
insert into Cars (Brand, Model, Year, Regnumber) values ('Toyota', 'Corolla', 1992, 'N17-11');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mitsubishi', 'Lancer', 2002, 'C15-31');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lexus', 'IS F', 2009, 'Z79-72');
insert into Cars (Brand, Model, Year, Regnumber) values ('Lamborghini', 'Aventador', 2012, 'Z65-33');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercury', 'Grand Marquis', 1998, 'A62-75');
insert into Cars (Brand, Model, Year, Regnumber) values ('Pontiac', 'Turbo Firefly', 1990, 'W32-67');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Terrain', 2010, 'Z94-68');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Suburban 1500', 2012, 'H43-59');
insert into Cars (Brand, Model, Year, Regnumber) values ('GMC', 'Savana 1500', 2007, 'N94-92');
insert into Cars (Brand, Model, Year, Regnumber) values ('Ford', 'Escort', 2000, 'G89-64');
insert into Cars (Brand, Model, Year, Regnumber) values ('Buick', 'Coachbuilder', 1995, 'W52-16');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercedes-Benz', 'E-Class', 1988, 'M98-11');
insert into Cars (Brand, Model, Year, Regnumber) values ('Chevrolet', 'Tahoe', 2012, 'B49-13');
insert into Cars (Brand, Model, Year, Regnumber) values ('Mercury', 'Villager', 1994, 'T82-68');
